
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml
  resources: !include ui-lovelace/resources.yaml
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /config/domain.cert.pem
  ssl_key: /config/private.key.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
light: !include lights.yaml
automation: !include automations.yaml
script: !include scripts.yaml

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info

homeassistant:
  packages: !include_dir_named packages
  media_dirs:
    music: /share/music

browser_mod:
prometheus:
