esphome:
  name: wemos_d1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret ssid1
  password: !secret ssid1_pass
  manual_ip:
    static_ip: !secret esphome_wemos_static_ip
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1
    dns2: !secret wifi_dns2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemos D1 Fallback Hotspot"
    password: "wzZeWXjOuWl5"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: neopixelbus
    type: GRB
    pin: GPIO03
    num_leds: 30
    name: "Leds Maartje"
    id: ledsmaartje1
    effects:
      # Use default parameters:
      - random:
      # Customize parameters
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - addressable_rainbow:
          name: Rainbow
          speed: 10
          width: 50
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False
      - addressable_scan:
      - addressable_twinkle:
      - addressable_fireworks:

binary_sensor:
  - platform: gpio
    name: "Leds Maartje Toggle"
    pin:
      number: D2
      mode: input_pullup
      inverted: true
    filters:
      - delayed_on: 10ms
    on_press:
      if:
        condition:
          light.is_on: ledsmaartje1
        then:
          light.turn_off: ledsmaartje1
        else:
          light.turn_on:
            id: ledsmaartje1
            effect: Rainbow

