sensor:
  - platform: afvalinfo
    resources:
      - gft
      - pbd
      - papier
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    location: !secret afvalinfo_city
    postcode: !secret afvalinfo_postalcode
    streetnumber: !secret afvalinfo_number
    dateformat: '%d-%m-%Y'
    locale: 'nl'
    timespanindays: 365